### ISSUE TITLE
Numbers in string format

### ISSUE THREAD

**Issue by bartbutenaers** [Woozinator/node-red-contrib-time-based-dimmer#1]
Hi @Woozinator ,

Thanks for sharing this contribution!
I advised last night your node to a friend of mine, but he got following values (for start value **10** and step value **20**): 

![image](https://user-images.githubusercontent.com/14224149/71548165-94738800-29aa-11ea-95be-b159953e5185.png)

I don't have his flow available at the moment, but I 'assume' it goes wrong in this code snippet:
```
newValue = oldValue + config.step
```
I am not familiar with Typescript, but in Javascript it could be solved like this:
```
newValue = oldValue + parseInt(config.step)
```
Otherwise the two strings are concatenated, resulting in the above screenshot.
Would be nice if you could handle also numbers that are delivered as string values...

Thanks!!
Bart

**Comment by woozar** [comment]
Thank you for the feedback. I can see the problem but I have no clue where it comes from. I will take a look and fix this, as soon as possible.
Btw parseInt is pretty much the same thing in TypeScript as in JavaScript.

**Comment by woozar** [comment]
@bartbutenaers I have applied a fix as you suggested and a matching test case. I hope i will solve your / your friends issue. It is contained in any version newer than 0.4.0

Please confirm

**Comment by woozar** [comment]
I will close the ticket now. It if doesn't work, please reopen.

**Comment by bartbutenaers** [comment]
Hi @Woozinator,

Thanks for your fast response!  And my best wishes for 2020!

Unfortunately the problem is not solved (with latest version), but now at least I can offer you a simple test flow so you can reproduce the problem:

![image](https://user-images.githubusercontent.com/14224149/71642698-8fb31a80-2caf-11ea-9380-74011ddb74de.png)

```
[{"id":"b833968a.fdbcc8","type":"inject","z":"ad3d4cf9.f7213","name":"brightness_up","topic":"","payload":"brightness_up","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":420,"wires":[["533def95.79798"]]},{"id":"ee50b2d9.9a29c","type":"inject","z":"ad3d4cf9.f7213","name":"brightness_down","topic":"","payload":"brightness_down","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":340,"y":460,"wires":[["533def95.79798"]]},{"id":"533def95.79798","type":"time-based-dimmer","z":"ad3d4cf9.f7213","name":"","interval":"500","step":"10","minValue":"10","maxValue":"50","startIncCommand":"brightness_up","stopIncCommand":"brightness_stop","startDecCommand":"brightness_down","stopDecCommand":"brightness_stop","x":570,"y":420,"wires":[["529262ed.f717fc"]]},{"id":"529262ed.f717fc","type":"debug","z":"ad3d4cf9.f7213","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":850,"y":420,"wires":[]},{"id":"a6fa2a19.59b4d8","type":"inject","z":"ad3d4cf9.f7213","name":"brightness_stop","topic":"","payload":"brightness_stop","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":340,"y":500,"wires":[["533def95.79798"]]}]
```
Steps to reproduce:
1. Press the '_brightness_up_' button.

1. Then everything goes well until at the end, when a "string" value appears:

   ![image](https://user-images.githubusercontent.com/14224149/71642711-eddffd80-2caf-11ea-8f5a-6c82151b1711.png)

1. Press the '_brightness_down_' button.

1. Then everything goes well until at the end, when again a "string" value appears:

   ![image](https://user-images.githubusercontent.com/14224149/71642733-2aabf480-2cb0-11ea-83a1-f5de9aa1ebb3.png)

1. Press the '_brightness_up_' button again.

1. Then it seems it is appending the string values, instead of adding the numbers:

   ![image](https://user-images.githubusercontent.com/14224149/71642746-57600c00-2cb0-11ea-83cb-1a3689849029.png)

Kind regards,
Bart

**Comment by woozar** [comment]
@bartbutenaers which version of node-red is that?

in the dimmer node in your config, i can see this configuration:

```
        "interval": "500",
        "step": "10",
        "minValue": "10",
        "maxValue": "50",
```

if i export the config of the node on my system, i can see this configuration:

```
        "interval": 500,
        "step": 10,
        "minValue": 10,
        "maxValue": 50,
```
I don't know why this is but as you can see the settings on your system are strings and on my system it is numbers. Could you try to remove the node and add it again?
To improve the user experience, I will add some code "on node creation" to convert all those values to numbers if they are strings.

**Comment by woozar** [comment]
I just added the code to convert all 4 config values from string to number when initializing the node.
Will be part of any release > 0.5.0

**Comment by bartbutenaers** [comment]
Hi @Woozinator,

Nice catch!  That is indeed weird.  Below my version numbers:

Node-RED version: v1.0.2
Node.js  version: v10.16.3

I'm going to close this issue because your latest version works fine now in my setup.  
Will ask my friend to test it also, but I assume it is solved now...

Thanks a lot for spending your time helping us!!!
Bart

**Comment by bartbutenaers** [comment]
It works fine for him too.  Great job!
