### ISSUE TITLE
not available in node-red pallet

### ISSUE THREAD

**Issue by carefulcomputer** [Woozinator/node-red-contrib-time-based-dimmer#11]
this node is not available in node-red pallet. can you please publish it node-red repo ?

**Comment by woozar** [comment]
What do you mean? In my node-red, I can install/update it from the pallet.

**Comment by carefulcomputer** [comment]
yes, i see it now. probably temporary glitch earlier. apologies for trouble.

**Comment by woozar** [comment]
Don't worry. It wasn't that much trouble ;)
