### ISSUE TITLE
Selectable output message field

### ISSUE THREAD

**Issue by bartbutenaers** [Woozinator/node-red-contrib-time-based-dimmer#3]
Hi @Woozinator,

Currently the calculated value always is send into the msg.payload field.  It would be nice if we could select the field ourselves, e.g. to reduce the number of Change nodes in our flow.

Moreover - if you would agree to implement our other [request ](https://github.com/Woozinator/node-red-contrib-time-based-dimmer/issues/2)- this becomes even more important.  Indeed the input message might e.g. already contain a payload field, which we might want to keep unchanged.

Something like this:

![image](https://user-images.githubusercontent.com/14224149/72021040-62e1a300-326d-11ea-87dd-1abd390da030.png)

If you would consider to implement this feature request, I 'think' you can do it like this:
+ Add this to the html:
   ```
    <div class="form-row">
        <label style="padding-top: 8px" for="node-input-outputField"><i class="fa fa-sign-out"></i> Output field</label>
        <input type="text" id="node-input-outputField" style="width:70%">
        <input type="hidden" id="node-input-outputFieldType">
    </div>
   ```
+ Add those properties to your "defaults" section (to use by default msg.payload):
   ```
   outputField: {value: "payload", required: true, validate: RED.validators.typedInput("outputFieldType")},
   outputFieldType: {value: "msg"},
   ```
+ Add this to the oneditprepare function:
   ```
   oneditprepare: function() {
     // Add the "msg" option in the dropdown list
     $('#node-input-outputField').typedInput({
         typeField: $("#node-input-outputFieldType"),
         types: ['msg']
     });
   }
   ```
+ And inside your tick function you could fill the specified output message field with your calculated value:
   ```
   var outputMessage = {}; // Or a clone of the input message, like in my other request
   RED.util.setMessageProperty(outputMessage, config.outputField, newValue, true);
   ```

P.S. If you would agree to implement this, we also need to make sure that existing flow containing your node are not impacted.    If you are interested, I have written down a few [tips ](https://discourse.nodered.org/t/upgrading-nodes-specifically-my-own/2641/11)some time ago.

Thanks a lot !!!
Bart

P.S. I have not created a pull-request, for the simple reason I'm not familiar with Typescript at the moment ...

**Comment by woozar** [comment]
I am sorry, but i will not change this at the moment. 
I explained my reasons in more detail in the other issue https://github.com/Woozinator/node-red-contrib-time-based-dimmer/issues/2
