### ISSUE TITLE
Can't install them in homeassistant

### ISSUE THREAD

**Issue by Davincible** [Woozinator/node-red-contrib-time-based-dimmer#5]
These nodes sound amazing, but i can't get them to work in home assistant. The build script you specified is not running, and therefore can't find the nodes.

I compared your package.json with [this one](https://github.com/rdmtc/node-red-contrib-sun-position), and they are not using a build script. Nodes are already located in the right folder. Maybe an approach like that could work.

Would really love to use these nodes.

**Comment by woozar** [comment]
I don't know anything about home assistant, but I will take a look.

**Comment by Davincible** [comment]
Thanks! I figured out it is because its written in typescript. But I don't know anything about typescript :)

**Comment by woozar** [comment]
You can try to translate the typescript. Just run yarn build and there will we js files in the dist folder. Maybe this will help.

**Comment by Davincible** [comment]
I was able to make it work by cloning the GitHub repository to my local machine, running the build command, and then manually uploading the dist folder. To make it HA compatible you could build it pre-release.

**Comment by woozar** [comment]
Oh fu** - I think this was all my failure. I didn't yet build a pipeline to publish new versions and it seems I just forgot to build the javascript files before uploading the latest version. :(
I hope I fixed it in the latest version 0.5.2
