### ISSUE TITLE
Dropping input node

### ISSUE THREAD

**Issue by Davincible** [Woozinator/node-red-contrib-time-based-dimmer#6]
It works great, only thing is that I have to use some values from the input msg (topic), the first single current brightness does not drop these, however, the dimming messages, do. It would be amazing if they would also include the input msg fields.

Tried to hack something together myself, but don't know typescript so didn't get very far.

**Comment by woozar** [comment]
I don't really understand, what you mean.

**Comment by woozar** [comment]
Please explain or I will close the ticket

**Comment by Davincible** [comment]
An input message can contain data parameters, and only the set_current_state message allows them to pass through, the messages that adjust the actual brightness drop all data parameters. This is probably because a new msg object is created. would be good to store the data that gets passed with the current state, and then also add that to the change of brightness messages

**Comment by woozar** [comment]
That would be a breaking change as the output payload is a plain number and replacing it by an object would change the behavior of existing nodes.
I will think about introducing a new setting for this...

**Comment by geoffreydemaagd** [comment]
What I miss a lot is that you can't pass the dimming value as input field. Therefore the slider in  node red for dimming is not in sync with the one buton dimmer node. Should be great if both nodes are on the samen brightness value.
Is it possible to add en optional inpput field in the one button dimmer with the current brightness value for example from a field or etc?

**Comment by woozar** [comment]
It was some time ago, that i wrote this node, but if i recall correctly, you can simply send a numerical value to the node and it will use it as its current value.

**Comment by woozar** [comment]
i just confirmed it in the code. both node types will use any input of type "number" as their new "current value".
