### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by Howesfam** [Woozinator/node-red-contrib-time-based-dimmer#7]
Attempting to install on Hass.io with Node red 6.1.3 (latest version), install fails with following errors

node-red-contrib-time-based-dimmer
0.5.2
Error: /config/node-red/node_modules/node-red-contrib-time-based-dimmer/dist/time-based-dimmer.html does not exist
Error: /config/node-red/node_modules/node-red-contrib-time-based-dimmer/dist/one-button-dimmer.html does not exist

**Comment by woozar** [comment]
I will take a look...

**Comment by geoffreydemaagd** [comment]
Hi Woozar, after the update of the one-time-button I also get the error in the logging of NR

6 Mar 10:48:43 - [info] Waiting for missing types to be registered:
6 Mar 10:48:43 - [info]  - one-button-dimmer

6 Mar 10:49:40 - [warn] [node-red-contrib-time-based-dimmer/time-based-dimmer] E                                         rror: /home/pi/.node-red/node_modules/node-red-contrib-time-based-dimmer/dist/ti                                         me-based-dimmer.html does not exist
6 Mar 10:49:40 - [warn] [node-red-contrib-time-based-dimmer/one-button-dimmer] E                                         rror: /home/pi/.node-red/node_modules/node-red-contrib-time-based-dimmer/dist/on                                         e-button-dimmer.html does not exist


Thanks

**Comment by woozar** [comment]
It seems that the results from the build are not part of the published package. I don't know why that is, though.

**Comment by woozar** [comment]
I had to add an array called "files" to my package.json file that includes the dist folder

**Comment by geoffreydemaagd** [comment]
> I had to add an array called "files" to my package.json file that includes the dist folder

Thanks for your help, when will it be published?

**Comment by woozar** [comment]
It already was, but node-red takes up to 2 hours until they list it as available update.

**Comment by Howesfam** [comment]
woozer,

Thanks for the quick response all working now, thanks for a very useful node
