### ISSUE TITLE
Incrementing not working with custom values for one-button-dimmer

### ISSUE THREAD

**Issue by HardcoreWR** [Woozinator/node-red-contrib-time-based-dimmer#9]
Hello,

When I use the 'one-button-dimmer' and change the default values, incrementing the dimlevel doesn't work properly.
When I press my button again to decrease the dimlevel everything is working as expected.
It looks as though any custom values are interpreted as string instead of integer.

![image](https://user-images.githubusercontent.com/10896064/77663049-e95c7580-6f7c-11ea-8d09-070e29a6c9eb.png)

Increasing fails:
![image](https://user-images.githubusercontent.com/10896064/77663014-df3a7700-6f7c-11ea-8539-63c45375efc0.png)

Decreasing is fine:
![image](https://user-images.githubusercontent.com/10896064/77663382-4821ef00-6f7d-11ea-8233-4994c37888aa.png)

If you need more information, let me know!

PS. Thanks for this functionality, very useful

**Comment by HardcoreWR** [comment]
Okay, not entirely true that decreasing works.
If I set the MaxValue to a custom value, increasing and decreasing the dimlevel gets real funny.

![image](https://user-images.githubusercontent.com/10896064/77669585-4bb97400-6f85-11ea-8654-59dcbf02d4f9.png)

Increasing:

![image](https://user-images.githubusercontent.com/10896064/77669715-7e636c80-6f85-11ea-85ea-f487972346ed.png)


Decreasing:

![image](https://user-images.githubusercontent.com/10896064/77669756-90dda600-6f85-11ea-9148-2120c1d26b8a.png)

Increasing after the last time decreasing:

![image](https://user-images.githubusercontent.com/10896064/77669827-a8b52a00-6f85-11ea-9634-412f6227573b.png)

**Comment by woozar** [comment]
I already had this bug before with the other dimmer. It seems that different node red versions handle the type of the variables differently.
I will fix it soon.
P.S. You're welcome

**Comment by woozar** [comment]
I just published a new version 0.7.0
I added type checks and conversions before doing the math.

@HardcoreWR Please check and report if it doesn't work.
(Might take up to 2 hours until the update is available in node-red)
